name: Build

on:
  workflow_dispatch:
  push:
    paths:
      - 'database/**'
      - 'core/**'
      - 'velocity/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        
      - name: Build Floodgate and SQLite Database
        # Fixed: Changed :database:sqlite:build to :sqlite:build
        run: ./gradlew :velocity:build :sqlite:build

      - name: Archive artifacts (Floodgate Velocity Proxy)
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: Floodgate Velocity
          path: velocity/build/libs/floodgate-velocity.jar
          if-no-files-found: error

      - name: Archive artifacts (Floodgate SQLite Database)
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: Floodgate SQLite Database
          path: database/sqlite/build/libs/floodgate-sqlite-database.jar
          if-no-files-found: error
